//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustOrderDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int ID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Product { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
